# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  web:
    image: mpharma_web
    privileged: true
    restart: always
    build:
      context: .
    environment:
      - FLASK_APP=autoapp.py
      - FLASK_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mpharma
      - SECRET_KEY="(*&RTJjhgf7ujKF3456)ojhgf3456765erdfghjkJRE"
      - PORT=5000
      - PGHOST=db
      - PGUSER=postgres
      - PGPORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mpharma
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
